### ISSUE TITLE
About using GPU implementation with python interface

### ISSUE THREAD

**Issue by haotianh9** [Treecodes/BaryTree#76]
Hello Dr. Wilson and Dr. Vaughn,

 Thank you so much for developing this great code. I'm a student trying to use your code in my research work, and I'm facing some problem with using the GPU implementation through python interface. 

  When compiling the code, since the newer version of PGI has been integrated in  [NVIDIA HPC SDK](https://www.pgroup.com/support/release_archive.php), I compiled the code using NVIDIA HPC SDK. Without changing the Cmakelist.txt file, it works. I've tested both "random_cube_gpu" and "random_cube_cpu" example works. In python interface, when I'm using cpu, it also works, but when I tried to use GPU, a bug is raised as follows. 

`Current file:     BaryTree/src/drivers/treedriver.c
        function: treedriver
        line:     385
This file was compiled: -acc=gpu -gpu=cc35 -gpu=cc50 -gpu=cc60 -gpu=cc60 -gpu=cc70 -gpu=cc75 -gpu=cc80 -`

I don't know whether you have any insight on this. Thank you for any help you can offer.

Yours sincerely,
Haotian

**Comment by lwwilson1** [comment]
Hi @haotianh9, thank you for using our code! Yes, NVIDIA HPC SDK is the way to go. I unfortunately have no experience using the python interface, but I vaguely recall issues with it along these lines. @njvaughn, I believe you encountered something similar at some point?

**Comment by njvaughn** [comment]
Hey @haotianh9, do you know which compute capability you need (cc##), and is it in the list?  At one point we did have to specify `cc60` for a certain machine.  If you look at the CMake file, you will see `-ta=tesla:ccall,cc60` in several places.  This is because for some reason, despite its name, `ccall` was not including `cc60`.  

Try adding your desired `cc` to those lines and recompile and let me know if that helps.  But I'm not sure that would explain why this only failed when using the python interface.  Are you calling the interface routines from your own project, or are you trying to run our provided python test?

**Comment by haotianh9** [comment]
Thank you both for you kindly reply. 
@njvaughn  before doing make, I did `export CC=nvc` before doing `cmake ..` 
There are several files containing `-ta=tesla:ccall,cc60`, such as `/build/src/CMakeFiles/BaryTree_gpu.dir/link.txt`, `/build/examples/CMakeFiles/random_cube_gpu.dir/flags.make` (totally 10 files). I don't know whether you mean I need to change them manually after calling cmake. And if I'm using `nvc`, how should I change this sentence `-ta=tesla:ccall,cc60`. Do I need to replace `cc60` or not? 
 
My ultimate goal is to use the interface in my own project (I won't make to much changes to the interface), but now the problem occurs in your provided python test? Thank you!

**Comment by njvaughn** [comment]
@haotianh9 Sorry for the confusion, there are two different meanings of "CC".  In one case, it is your "C-Compiler".  You set this to `nvc`, which should be fine, although I thought it would be `nvcc`, maybe @lwwilson1 can confirm.

The other meaning of "CC" is "Compute-Capability".  Different NVIDIA GPUs have different compute capabilities, which just defines what hardware/software capabilities they have.  What you need to do is the following:
1) identify what _model_ of GPU you are trying to run on.  We ran on all the Tesla models, Telsa K40, K80, P100, V100.  
2) identify the _Compute Capability_ of your GPU.  Will be something like cc35, cc60, cc80, etc.  There is a table on wikipedia https://en.wikipedia.org/wiki/CUDA.
3) Look at your error message.  It says `This file was compiled: -acc=gpu -gpu=cc35 -gpu=cc50 ...` etc.  Check if your desired CC is in that list.
4a) If your desired CC is _NOT_ in that list, then manually edit the CMake file to include it.  You could simply replace the instances of `cc60` with your own. 
4b) If your desired CC is already in that list, then report back to me, because I will need to do some digging.

**Comment by haotianh9** [comment]
@njvaughn Thank you so much! It works after changing `cc60` to the computer capacity of my GPU! 

Actually I tried `nvcc` at the beginning, but it cannot find my MPI package. When I'm using `nvc` it has no such problem. 

There is a small concern which I don't know whether this is important or not. In the python example you provided, there are very strict accuracy check ( 1E-14). When previously I was trying the CPU implementation, I can only get error in the order of 1E-13. When using GPU now, for [specifying  theta](https://github.com/Treecodes/BaryTree/blob/ee3f0390edb3fbc3d2003a9994cabd0c0742c702/interfaces/python/testBaryTreeInterface.py#L61), I can also get error in the order of 1E-13, however, for the case of [specifying beta](https://github.com/Treecodes/BaryTree/blob/ee3f0390edb3fbc3d2003a9994cabd0c0742c702/interfaces/python/testBaryTreeInterface.py#L76), the error is much larger `0.00644`. I don't know what is the problem about this. Thank you!

**Comment by njvaughn** [comment]
Awesome!  I hope it helps your project, let me and Leighton know how everything goes.

If the errors are 1E-13 that is fine, there is going to be machine precision roundoff errors.  If we used the same compilers and ran on the same machines, then we should be within the 1E-14.  Since that's not the case, it's not surprising, and we might want to loosen the tolerance just so it doesn't concern people.

For the error when specifying beta, that is too large.  Beta is an attempt to automate the selection of treecode paramters (theta, degree, target leaf size, source leaf size).  We were tinkering with this towards the end of the project, it's possible we modified how beta selects these parameters but forgot to update the test.  I wouldn't worry about it if I were you.  

I'd say you can go ahead and use BaryTree in your project at this point.  What is your project by the way?  Do we already have the kernel function(s) that you'll need?

**Comment by haotianh9** [comment]
Thank you so much for your kindly explanation. Thus, probably I should not use beta, instead I need to specify theta, degree and other parameters as suggested in your examples.

My project is about using [Vortex sheet method](http://www.math.lsa.umich.edu/~krasny/paper-jfm-94.pdf) (which is also developed by your group) for solving fluid structure interaction problems. I already have a [paper](https://www.cambridge.org/core/journals/journal-of-fluid-mechanics/article/active-tail-flexion-in-concert-with-passive-hydrodynamic-forces-improves-swimming-speed-and-efficiency/48413CCD6F1D885E7C39FDDFE58E1798) on this, and will further move on to more complex problems. Thus I need to use FMM/Treecode to accelerate my computation. 

The kernel function I'm using is the regularized Biot Savart kernel function, which is already provided by you. Probably I'll be thinking of revising your code a little bit in order to calculate RBS_U and RBS_V simultaneously. 

Thank you again for your kindly support and great code!

**Comment by njvaughn** [comment]
Ahh very nice, I’ve been learning more about FSI and other mesh-coupling methods the past year or so.  Would be nice to see BaryTree contribute to one.  Well good luck and let us know if you run into any more issues along the way or want to show off any cool results.

**Comment by haotianh9** [comment]
Thank you so much!
